urls:
  - https://marshal.ohtly.com/index.html
domainWhitelist:
  - marshal.ohtly.com
maxDepth: 10
timeout: !!int 10000 #超时
interval: !!int 500 #请求间隔
maxConcurrency: 10 #同时的请求数
respectRobotsTxt: false
debug: false
rules:
  fetch:
    - !!js/regexp ^\/page\/(\d*)\/ # 列表分页
    - !!js/regexp \/([1-3]\d{3}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])).* # 文章
  parse:
    - !!js/regexp \/([1-3]\d{3}\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])).* # 文章
